require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

# Naming
Naming/FileName:
  Exclude:
    - 'lib/jekyll-notion-cms.rb'

# Gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 45

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 12

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Lint
Lint/DuplicateBranch:
  Enabled: false

# RSpec
RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

# Capybara
Capybara/RSpec/PredicateMatcher:
  Enabled: false
